[hooks]
pre = ["per-script.rhai"]
post = ["post-script.rhai"]

[placeholders.grpc_package]
type = "string"
prompt = "Grpc package name?"

[placeholders.grpc_port]
type = "string"
prompt = "Grpc port?"
default = "8888"

[placeholders.grpc_service_name]
type = "string"
prompt = "Grpc service name?"

[placeholders.is_seq_enabled]
type = "bool"
prompt = "Want to use seq logger?"
default = true

[placeholders.is_use_psql]
type = "bool"
prompt = "Will you use PostgreSQL?"
default = false

[placeholders.is_use_telemetry]
type = "bool"
prompt = "Will you use MyTelemetry?"
default = false

[placeholders.is_use_nosql]
type = "string"
prompt = "Will you use MyNoSql and how?"
choices = ["reader", "writer", "both", "no"]
default = "no"

[placeholders.is_use_sb]
type = "string"
prompt = "Will you use Service Bus and how?"
choices = ["publisher", "subscriber", "both", "no"]
default = "no"

[template]
ignore = [ 
  "./templates",
  "./.git",
  "./internal",
  "./readme.MD",
]