name: Release App
on:
  push:
    tags: "*"

env:
  REGISTRY: test
  IMAGE_NAME: test


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1             
      - run: cargo build --release

      - name: Get current time
        uses: MyJetTools/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
          utcOffset: "+00:00"     

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |          
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin   
      
      - name: Build and publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./
          registry: ${REGISTRY}
          repository: ${IMAGE_NAME}
          tags: ${{ steps.get_version.outputs.VERSION }}
          add_git_labels: true
          build_args: app_version=${{ steps.get_version.outputs.VERSION }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}